### ISSUE TITLE
Javascript Errors on Backspace

### ISSUE THREAD

**Issue by mbillow** [rux-pizza/discourse-awesome-bbcodes#3]
This line is causing large numbers of Javascript errors.

https://github.com/rux-pizza/discourse-awesome-bbcodes/blob/18f8c1b4a1f79c14a498435326b19d29098fa316/assets/javascripts/jquery/autocomplete-tag.js.es6#L216

```
Uncaught TypeError: Cannot read property 'caretPosition' of undefined
    at HTMLTextAreaElement.<anonymous> (_plugin-third-party-15cd8ed….js:443)
    at HTMLTextAreaElement.dispatch (_ember_jquery-60dedd1….js:7)
    at HTMLTextAreaElement.g.handle (_ember_jquery-60dedd1….js:7)
```

**Comment by masda70** [comment]
Thanks for reporting. Unfortunately the plugin is out of date and we are still using the old API. We will be updating soon.

**Comment by masda70** [comment]
Fixed by https://github.com/rux-pizza/discourse-awesome-bbcodes/commit/d79aeeaae56c660d41ce0e7fd4f596fd5a2f5cf6
Merged with https://github.com/rux-pizza/discourse-awesome-bbcodes/commit/128c5598088b236952b6cfdbca605d344b5cd90e
